package com.sebone.deliveringsmiles.interfaces;

import java.util.List;
import java.time.*;
import com.sebone.deliveringsmiles.dataclass.OrderStatus;
import com.sebone.deliveringsmiles.dataclass.PayoutData;
/**Interface name:-Payout 
 * Objective:-This interface contain 3 methods . we declare all the methods regarding payouts, like what is the amount of the money the driver got from a particular order, what is the monthly payout generated by the driver and all the things. 
 * @author:-Shreya paliwal
 * Date-24/03/2022
*/
public interface Payout {
	PayoutData payoutByOrder(int orderId ,int driverId);
	List<PayoutData> payoutOfTheDays(OrderStatus orderStatus,int driverId,LocalDate startDate,LocalDate endDate);
	List<PayoutData> totalPayout(int driverId);
}
